<?php
/**
 * Created by PhpStorm.
 * User: fedo
 * Date: 5/12/2017
 * Time: 2:57 PM

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 */


$buff1 = 1;
$buff2= 1;
$total=0;
$sum = 0;
while($total < 4000000){
	$total = $buff1+ $buff2;
	$buff2 = $buff1;
	$buff2 = $total;

	if($total % 2 === 0){
		$sum +=$total;
	}
}

echo "Total is $sum";